services:
  BT_SERVICE_NAME6:
    image: joyqi/typecho:${VERSION}-php8.0-apache
    #    container_name: ${CONTAINER_NAME}
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    restart: always
    environment:
      - TYPECHO_INSTALL=1
      - TYPECHO_DB_ADAPTER=${TYPECHO_DB_ADAPTER}
      - TYPECHO_DB_HOST=${MYSQL_HOST_IP}
      - TYPECHO_DB_DATABASE=${MYSQL_DATABASE}
      - TYPECHO_DB_PORT=${MYSQL_PORT}
      - TYPECHO_DB_USER=${MYSQL_USER}
      - TYPECHO_DB_PASSWORD=${MYSQL_PASSWORD}
      - TYPECHO_USER_NAME=${TYPECHO_USER_NAME}
      - TYPECHO_USER_PASSWORD=${TYPECHO_USER_PASSWORD}
      - TYPECHO_USER_MAIL=${TYPECHO_USER_MAIL}
      - TYPECHO_SITE_URL=${TYPECHO_EXTERNAL_URL}
    ports:
      - ${HOST_IP}:${WEB_HTTP_PORT}:80
    volumes:
      - ${APP_PATH}/data:/app
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true