services:
  BT_SERVICE_NAME6:
    image: portainer/portainer-ce:${VERSION}
    #    container_name: ${CONTAINER_NAME}
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    restart: always
    ports:
      - ${HOST_IP}:${WEB_HTTP_PORT}:9000
      - ${HOST_IP}:${API_PORT}:8000
    volumes:
        - ${APP_PATH}/data:/data
        - /var/run/docker.sock:/var/run/docker.sock
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true