services:
  languagetool:
    image: erikvl87/languagetool:${VERSION:-latest}
    ports:
      - "${LANGUAGETOOL_WEB_PORT}:8010"
    volumes:
      - "${APP_PATH}/data/logback.xml:/LanguageTool/logback.xml"
    restart: always
    deploy:
      resources:
        limits:
          cpus: "${CPUS}"
          memory: "${MEMORY_LIMIT}"
    labels:
      createdBy: "bt_apps"

networks:
  default:
    name: baota_net
    external: true