# 端口号
server.port=80

# redis 的 host
redis.host=redis
# redis 的端口号
#redis.port=6379
# 如果你的redis没有密码，就不要设置 redis.password ，如果有密码，才设置
#redis.password=

#
# 翻译缓存
# 使用缓存能力的前提是已经购买了付费版本填入了授权码
#
# 文件缓存，默认不设置是启用
#cache.file.use=true
# 内存缓存，默认不设置是不启用。 true为启用
#cache.memory.use=true

# 翻译通道。如果你配置了其他翻译通道，你需要把这个给注释掉！切记
translate.service.leimingyun.domain=http://api.translate.zvo.cn
#translate.service.leimingyun.key=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

# 通过翻译通道进行翻译文本时，翻译通道每次最多允许同时传入多少要翻译的文字（单纯就是长度，比如 “你好”长度是2， “hello” 长度是5）
# 不设置时默认为0，表示不限制。
# 比如设置为3，实际翻译接口传入了4段要翻译的文本，第一段是2个字符，第二段是4个字符，第三段是7个字符，第四段是5个字符 那会将其拆分为4次请求，向翻译通道发起4次http请求。
#   如果设置为6，那上面的4段文本就会拆分为 三次请求，第一段跟第二段 是一次， 第三段是一次、第四段是一次。
#   如果设置为15，那上面的4段文本就会拆分为 2次请求，第一段、第二段、第三段 这三段是一次， 第四段是一次。
#   如果设置为1，那么肯定每段文本都会大于等于1，也就是每段都是一次请求，一共4段，共4次请求。
# 注意，使用大模型的通道才有这个，值越小，大模型越精准不易出错。
#translate.service.set.requestMaxSize=1

# 启用的线程数，大模型翻译，还可以给其配置多线程，来进行大幅提升翻译速度。  https://translate.zvo.cn/391752.html
#translate.service.set.threadNumber=2

# 公开版本的每日最大翻译字数，也就是通过 translate.json 接口翻译的字符数。注意这是字符的个数。比如“你好”是两个字符，“hello” 是五个字符，它统计的是翻译结果的字符。
# 这里配置后，将会对域名进行限制，凡是未出现在 domain.json 配置中的域名，它的日上限就是这么多。它的目的是为了避免你的接口被人恶意利用。 注意这个功能需要配置了授权码后才能生效
# 如果设置为0，则是不允许陌生人访问，必须是出现在 domain.json 中的域名或key才能访问使用。
# 它基本是配合 /mnt/service/domain.json 来一起使用的，有关这个的说明，可以参考 https://translate.zvo.cn/391130.html
#public.dayMaxSize=10000



# 付费企业版 解锁 大模型通道多线程提速、内存缓存、翻译字符统计、陌生者使用的每日翻译上限、域名白名单、文本翻译接口的key、管理后台 ...  详情参考 https://translate.zvo.cn/391753.html
#authorize=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx