services:
  BT_SERVICE_NAME6:
    image: onlyoffice/documentserver:${VERSION}
    #    container_name: ${CONTAINER_NAME}
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    restart: always
    ports:
      - ${HOST_IP}:${WEB_HTTP_PORT}:80
    volumes:
      - ${APP_PATH}/logs:/var/log/onlyoffice
      - ${APP_PATH}/data:/var/www/onlyoffice/Data
      - ${APP_PATH}/lib:/var/lib/onlyoffice
      - ${APP_PATH}/db:/var/lib/postgresql
    environment:
      - JWT_SECRET=${JWT_SECRET}
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true