services:
  BT_SERVICE_NAME6:
    image: advplyr/audiobookshelf:${VERSION}
    #    container_name: ${CONTAINER_NAME}
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    restart: always
    ports:
      - ${HOST_IP}:${WEB_HTTP_PORT}:80
    volumes:
      - ${APP_PATH}/audiobooks:/audiobooks
      - ${APP_PATH}/podcasts:/podcasts
      - ${APP_PATH}/config:/config
      - ${APP_PATH}/metadata:/metadata
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true