services:
  BT_SERVICE_NAME6:
    image: odoo:17.0
    depends_on:
      - db
    ports:
      - ${HOST_IP}:${WEB_HTTP_PORT}:8069
    volumes:
      - ${APP_PATH}/data:/var/lib/odoo
      - ${APP_PATH}/addons:/mnt/extra-addons
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - ${APP_PATH}/db:/var/lib/postgresql/data
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true
