services:
  BT_SERVICE_NAME6:
    image: wbsu2003/koodo-reader:${VERSION}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}    
    ports:
      - ${HOST_IP}:${WEB_HTTP_PORT}:80
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true