services:
  BT_SERVICE_NAME6:
    image: nacos/nacos-server:${VERSION}
    #    container_name: ${CONTAINER_NAME}
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    restart: always
    ports:
      - ${HOST_IP}:${WEB_PORT}:8080
      - ${HOST_IP}:${WEB_HTTP_PORT}:8848
      - ${HOST_IP}:${WEB_COMMUNICATION_PORT}:9848
    environment:
      - NACOS_AUTH_ENABLE=TRUE
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - JVM_XMS=${JVM_XMS}
      - JVM_XMX=${JVM_XMX}
      - JVM_XMN=${JVM_XMN}
      - JVM_MS=${JVM_MS}
      - JVM_MMS=${JVM_MMS}
      - NACOS_AUTH_IDENTITY_KEY=${NACOS_AUTH_IDENTITY_KEY}
      - NACOS_AUTH_IDENTITY_VALUE=${NACOS_AUTH_IDENTITY_VALUE}
      - NACOS_AUTH_TOKEN=${NACOS_AUTH_TOKEN}
      - NACOS_SERVER_IP=${NACOS_SERVER_IP}
    volumes:
      - ${APP_PATH}/logs:/home/nacos/logs
      - ${APP_PATH}/data:/home/nacos/data
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true