services:
  zincsearch:
    image: public.ecr.aws/zinclabs/zincsearch:latest
    container_name: zincsearch
    restart: always
    ports:
      - "${HOST_IP}:${WEB_HTTP_PORT}:4080"
    environment:
      ZINC_FIRST_ADMIN_USER: ${ZINC_FIRST_ADMIN_USER}
      ZINC_FIRST_ADMIN_PASSWORD: ${ZINC_FIRST_ADMIN_PASSWORD}
      ZINC_DATA_PATH: "/data"
    volumes:
      - "${APP_PATH}/data:/data"
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true