services:
  BT_SERVICE_NAME6:
    image: roundcube/roundcubemail:${VERSION}-apache
    #    container_name: ${CONTAINER_NAME}
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    restart: always
    environment:
      ROUNDCUBEMAIL_DB_TYPE: mysql
      ROUNDCUBEMAIL_DB_HOST: ${ROUNDCUBEMAIL_HOST}
      ROUNDCUBEMAIL_DB_PORT: ${ROUNDCUBEMAIL_PORT}
      ROUNDCUBEMAIL_DB_USER: ${ROUNDCUBEMAIL_USER}
      ROUNDCUBEMAIL_DB_PASSWORD: ${ROUNDCUBEMAIL_PASSWORD}
      ROUNDCUBEMAIL_DB_NAME: ${ROUNDCUBEMAIL_NAME}
      ROUNDCUBEMAIL_DEFAULT_HOST: ${IMAP_SERVER}
      ROUNDCUBEMAIL_DEFAULT_PORT: ${IMAP_SERVER_PORT}
      ROUNDCUBEMAIL_SMTP_SERVER: ${SMTP_SERVER}
      ROUNDCUBEMAIL_SMTP_PORT: ${SMTP_SERVER_PORT}
      ROUNDCUBEMAIL_UPLOAD_MAX_FILESIZE: 5M
    ports:
      - ${WEB_HTTP_PORT}:80
    volumes:
      - ${APP_PATH}/data:/var/www/html
      - ${APP_PATH}/logs:/var/log/apache2
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true