services:
  BT_SERVICE_NAME6:
    image: bestoray/pgyserver:${VERSION}
    #    container_name: ${CONTAINER_NAME}
    restart: always
    devices:
      - /dev/net/tun
    privileged: true
    environment:
      - PGY_USERNAME=${PGY_USERNAME}
      - PGY_PASSWORD=${PGY_PASSWORD}
    labels:
      createdBy: "bt_apps"
    network_mode: host
