services:
  BT_SERVICE_NAME6:
    image: cppla/serverstatus:${VERSION}
    #    container_name: ${CONTAINER_NAME}
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    restart: unless-stopped
    ports:
      - ${HOST_IP}:${WEB_HTTP_PORT}:80
      - ${HOST_IP}:${SERVER_PORT}:35601      
    volumes:
      - ${APP_PATH}/config.json:/ServerStatus/server/config.json
      - ${APP_PATH}/web/json:/usr/share/nginx/html/json
    healthcheck:
      test: curl --fail http://localhost:80 || bash -c 'kill -s 15 -1 && (sleep 10; kill -s 9 -1)'
      interval: 30s
      timeout: 10s
      retries: 5
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true