services:
  BT_SERVICE_NAME6:
    image: axigen/axigen:${VERSION}
    #    container_name: ${CONTAINER_NAME}
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    restart: always
    ports:
      - ${HOST_IP}:${WEB_HTTP_PORT}:80
      - ${HOST_IP}:${WEB_HTTPS_PORT}:443
      - ${HOST_IP}:${IMAP_SSL_PORT}:993
      - ${HOST_IP}:${POP3_SSL_PORT}:995
      - ${HOST_IP}:${SMTP_PORT}:25
      - ${HOST_IP}:${SMTP_SSL_PORT}:465
      - ${HOST_IP}:${CLI_PORT}:7000
      - ${HOST_IP}:${WEB_ADMIN_PORT}:9000
      - ${HOST_IP}:${WEB_ADMIN_SSL_PORT}:9443
    volumes:
      - ${APP_PATH}/data:/axigen/var
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true