services:
  BT_SERVICE_NAME6:
    image: apache/streampark:${VERSION}
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    ports:
      - ${HOST_IP}:${WEB_HTTP_PORT}:10000
    environment:
      - TZ=Asia/Shanghai
      - DATASOURCE_DIALECT=h2 # h2, mysql, pgsql
#     If use mysql or pgsql, please set the following parameters
#     - DATASOURCE_URL=jdbc:mysql://localhost:3306/streampark?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
#     - DATASOURCE_URL=jdbc:postgresql://localhost:5432/streampark?stringtype=unspecified
#     - DATASOURCE_USERNAME=root
#     - DATASOURCE_PASSWORD=streampark
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/hosts:/etc/hosts:ro
      - ~/.kube:/root/.kube:ro
    privileged: true
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "http://BT_SERVICE_NAME6:10000" ]
      interval: 5s
      timeout: 5s
      retries: 120
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net
      
networks:
  baota_net:
    external: true