services:
  serpbear:
    image: towfiqi/serpbear
    restart: always
    ports:
      - "${HOST_IP}:${SERPBEAR_WEB_PORT}:3000"
    volumes:
      - ${APP_PATH}/data:/app/data
    environment:
      - USER=${USER}
      - PASSWORD=${PASSWORD}
      - SECRET=${SECRET}
      - APIKEY=${APIKEY}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
    deploy:
      resources:
        limits:
          cpus: "${CPUS}"
          memory: "${MEMORY_LIMIT}"
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true