services:
  monica-app:
    image: library/monica:${VERSION}
    environment:
      - DB_HOST=monica-db
      - DB_USERNAME=monica
      - DB_PASSWORD=monica
    depends_on:
      - monica-db
    ports:
      - "${HOST_IP}:${MONICA_WEB_PORT}:80"
    volumes:
      - ${APP_PATH}/data/storage:/var/www/html/storage
    restart: always
    deploy:
      resources:
        limits:
          cpus: "${CPUS}"
          memory: "${MEMORY_LIMIT}"
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

  monica-db:
    image: mariadb:11
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=monica
      - MYSQL_USER=monica
      - MYSQL_PASSWORD=monica
    volumes:
      - ${APP_PATH}/data/mysql:/var/lib/mysql
    restart: always
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true