services:
  BT_SERVICE_NAME6:
    image: jinzeyang/whois:${VERSION}
    restart: always
    ports:
      - ${HOST_IP}:${WEB_HTTP_PORT}:8043
    depends_on:
        - redis
    links:
        - redis
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net
      
  redis:
    image: redis:latest
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true