services:
  erpnext_backend:
    image: frappe/erpnext:v${VERSION}
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    environment:
      DB_HOST: erpnext_db
      DB_PORT: "3306"
      MYSQL_ROOT_PASSWORD: admin
      MARIADB_ROOT_PASSWORD: admin

  configurator:
    image: frappe/erpnext:v${VERSION}
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net
    deploy:
      restart_policy:
        condition: none
    entrypoint:
      - bash
      - -c
    command:
      - >
        ls -1 apps > sites/apps.txt;
        bench set-config -g db_host $$DB_HOST;
        bench set-config -gp db_port $$DB_PORT;
        bench set-config -g redis_cache "redis://$$REDIS_CACHE";
        bench set-config -g redis_queue "redis://$$REDIS_QUEUE";
        bench set-config -g redis_socketio "redis://$$REDIS_QUEUE";
        bench set-config -gp socketio_port $$SOCKETIO_PORT;
    environment:
      DB_HOST: erpnext_db
      DB_PORT: "3306"
      REDIS_CACHE: erpnext_redis-cache:6379
      REDIS_QUEUE: erpnext_redis-queue:6379
      SOCKETIO_PORT: "9000"
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  create-site:
    image: frappe/erpnext:v${VERSION}
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net
    deploy:
      restart_policy:
        condition: none
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    entrypoint:
      - bash
      - -c
    command:
      - >
        wait-for-it -t 120 erpnext_db:3306;
        wait-for-it -t 120 erpnext_redis-cache:6379;
        wait-for-it -t 120 erpnext_redis-queue:6379;
        export start=`date +%s`;
        until [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".db_host // empty"` ]] && \
          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_cache // empty"` ]] && \
          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_queue // empty"` ]];
        do
          echo "Waiting for sites/common_site_config.json to be created";
          sleep 5;
          if (( `date +%s`-start > 120 )); then
            echo "could not find sites/common_site_config.json with required keys";
            exit 1
          fi
        done;
        echo "sites/common_site_config.json found";
        bench new-site --mariadb-user-host-login-scope='%' --admin-password=admin --db-root-username=root --db-root-password=admin --install-app erpnext --set-default frontend;

  erpnext_db:
    image: mariadb:10.6
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net
    healthcheck:
      test: mysqladmin ping -h localhost --password=admin
      interval: 1s
      retries: 20
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MARIADB_ROOT_PASSWORD: admin
    volumes:
      - db-data:/var/lib/mysql

  erpnextf_rontend:
    image: frappe/erpnext:v${VERSION}
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net
    depends_on:
      - erpnext_websocket
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - nginx-entrypoint.sh
    environment:
      BACKEND: erpnext_backend:8000
      FRAPPE_SITE_NAME_HEADER: frontend
      SOCKETIO: erpnext_websocket:9000
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: "off"
      PROXY_READ_TIMEOUT: 120
      CLIENT_MAX_BODY_SIZE: 50m
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    ports:
      - "${HOST_IP}:${WEB_HTTP_PORT}:8080"

  erpnext_queue-long:
    image: frappe/erpnext:v${VERSION}
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - worker
      - --queue
      - long,default,short
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  erpnext_queue-short:
    image: frappe/erpnext:v${VERSION}
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - worker
      - --queue
      - short,default
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  erpnext_redis-queue:
    image: redis:6.2-alpine
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - redis-queue-data:/data

  erpnext_redis-cache:
    image: redis:6.2-alpine
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net
    deploy:
      restart_policy:
        condition: on-failure

  erpnext_scheduler:
    image: frappe/erpnext:v${VERSION}
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - schedule
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  erpnext_websocket:
    image: frappe/erpnext:v${VERSION}
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - node
      - /home/frappe/frappe-bench/apps/frappe/socketio.js
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${APP_PATH}/data/db-data
  redis-queue-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${APP_PATH}/data/redis-queue-data
  sites:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${APP_PATH}/data/sites
  logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${APP_PATH}/data/logs
networks:
  baota_net:
    external: true