services:
  BT_SERVICE_NAME6:
    image: crazymax/flarum:${VERSION}
    #    container_name: ${CONTAINER_NAME}
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    restart: always
    ports:
      - ${WEB_HTTP_PORT}:8000
    environment:
      - TZ=Asia/Shanghai
      - PUID=1000
      - PGID=1000
      - MEMORY_LIMIT=256M
      - UPLOAD_MAX_SIZE=256M
      - CLEAR_ENV=yes
      - OPCACHE_MEM_SIZE=128M
      - LISTEN_IPV6=true
      - REAL_IP_FROM=0.0.0.0/32
      - DB_HOST=${MYSQL_HOST_IP}
      - DB_PORT=${MYSQL_PORT}
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_PREFIX=${MYSQL_PREFIX}
      - DB_NOPREFIX=false
      - DB_TIMEOUT=60
      - FLARUM_BASE_URL=${FLARUM_BASE_URL}
    volumes:
      - ${APP_PATH}/data:/data
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true