services:
  crmeb_mysql:
    image: registry.cn-zhangjiakou.aliyuncs.com/xazbkj/mysql:5.7
    hostname: crmeb_mysql
    restart: always
    environment:
      TZ: Asia/Shanghai
    working_dir: /var/www/html
    labels:
      createdBy: "bt_apps"
    volumes:
      - ${APP_PATH}/app/mysql/data:/var/lib/mysql
    networks:
      - baota_net
      
  BT_SERVICE_NAME6:
    image: registry.cn-zhangjiakou.aliyuncs.com/xazbkj/crmeb_ky:${VERSION}
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}    
    restart: always
    ports:
      - ${HOST_IP}:${WEB_HTTP_PORT}:80
    #   - 40001:40001
    #   - 40002:40002
    #   - 40003:40003
    working_dir: /var/www/html
    depends_on:
      - crmeb_mysql
    environment:
      MYSQL_HOST_IP: crmeb_mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: crmeb-php
      REDIS_HOST_IP: 127.0.0.1
      REDIS_PORT: 6379
      REDIS_DATABASE: 0
    entrypoint: ["/crmeb-script.sh"]
    tmpfs: /var/www/temp #上传临时文件夹
    volumes:
      - ${APP_PATH}/app/crmeb/public/upload:/var/www/html/public/uploads
    #   - ./crmeb.env:/var/www/html/.env #程序缓存目录
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net
      
networks:
  baota_net:
    external: true

      
      