services:
  watchyourlan:
    image: aceberg/watchyourlan:latest
    ports:
      - "${HOST_IP}:${WATCHYOURLAN_WEB_PORT}:8840"
    restart: always
    volumes:
      - ${APP_PATH}/data:/data
    environment:
      - TZ=${TZ}
      - GUIIP=${HOST_IP}
      - GUIPORT=${WATCHYOURLAN_WEB_PORT}
      - IFACE=${IFACE}
      - THEME=${THEME}
    deploy:
      resources:
        limits:
          cpus: "${CPUS}"
          memory: "${MEMORY_LIMIT}"
    labels:
      createdBy: "bt_apps"
    network_mode: host