services:
    pgsql-billionmail:
      image: postgres:17.4-alpine
      hostname: pgsql
      volumes:
        - ${APP_PATH}/data/postgresql-data:/var/lib/postgresql/data
        - ${APP_PATH}/data/postgresql-socket:/var/run/postgresql
      environment:
        - TZ=${TZ}
        - POSTGRES_DB=${DBNAME}
        - POSTGRES_USER=${DBUSER}
        - POSTGRES_PASSWORD=${DBPASS}
      restart: always
      ports:
        - "${SQL_PORT:-127.0.0.1:25432}:5432"
      labels:
        createdBy: "bt_apps"

    redis-billionmail:
      image: redis:7.4.2-alpine
      hostname: redis
      entrypoint: ["/bin/sh","/redis-conf.sh"]
      volumes:
        - ${APP_PATH}/data/redis-data:/data
        - ${APP_PATH}/conf/redis/redis-conf.sh:/redis-conf.sh
      restart: always
      ports:
        - "${REDIS_PORT:-127.0.0.1:26379}:6379"
      environment:
        - TZ=${TZ}
        - REDISPASS=${REDISPASS}
      sysctls:
        - net.core.somaxconn=4096
      labels:
        createdBy: "bt_apps"

    rspamd-billionmail:
      image: billionmail/rspamd:1.1
      hostname: rspamd
      depends_on:
        - redis-billionmail
      environment:
        - TZ=${TZ}
        - REDISPASS=${REDISPASS}
      volumes:
        - ${APP_PATH}/conf/rspamd/local.d:/etc/rspamd/local.d
        - ${APP_PATH}/conf/rspamd/statistic.conf:/etc/rspamd/statistic.conf
        - ${APP_PATH}/conf/rspamd/rspamd.conf:/etc/rspamd/rspamd.conf
        - ${APP_PATH}/data/rspamd-data:/var/lib/rspamd
        - ${APP_PATH}/data/logs/rspamd:/var/log/rspamd
      restart: always
      labels:
        createdBy: "bt_apps"

    dovecot-billionmail:
      image: billionmail/dovecot:1.4
      hostname: dovecot
      depends_on:
        - pgsql-billionmail
        - redis-billionmail
      cap_add:
        - NET_BIND_SERVICE
      volumes:
        - ${APP_PATH}/conf/dovecot/conf.d:/etc/dovecot/conf.d
        - ${APP_PATH}/conf/dovecot/dovecot.conf:/etc/dovecot/dovecot.conf
        - ${APP_PATH}/conf/dovecot/rsyslog.conf:/etc/rsyslog.conf
        - ${APP_PATH}/data/logs/dovecot:/var/log/mail
        - ${APP_PATH}/data/ssl:/etc/ssl/mail
        - ${APP_PATH}/ssl-self-signed:/etc/ssl/ssl-self-signed
        - ${APP_PATH}/data/vmail-data:/var/vmail
        - ${APP_PATH}/data/rspamd-data:/var/lib/rspamd
        - ${APP_PATH}/data/postgresql-socket:/var/run/postgresql
      environment:
        - DBNAME=${DBNAME}
        - DBUSER=${DBUSER}
        - DBPASS=${DBPASS}
        - TZ=${TZ}
        - BILLIONMAIL_HOSTNAME=${BILLIONMAIL_HOSTNAME}
        - REDISPASS=${REDISPASS}
      ports:
        - "${IMAP_PORT:-143}:143"
        - "${IMAPS_PORT:-993}:993"
        - "${POP_PORT:-110}:110"
        - "${POPS_PORT:-995}:995"
      restart: always
      ulimits:
        nproc: 65535
        nofile:
          soft: 20000
          hard: 40000
      labels:
        createdBy: "bt_apps"

    postfix-billionmail:
      image: billionmail/postfix:1.5
      hostname: postfix
      depends_on:
        pgsql-billionmail:
          condition: service_started
      volumes:
        - ${APP_PATH}/conf/postfix/main.cf:/etc/postfix/main.cf
        - ${APP_PATH}/conf/postfix/master.cf:/etc/postfix/master.cf
        - ${APP_PATH}/conf/postfix/conf:/etc/postfix/conf
        - ${APP_PATH}/conf/postfix/sql:/etc/postfix/sql
        - ${APP_PATH}/conf/postfix/rsyslog.conf:/etc/rsyslog.conf
        - ${APP_PATH}/data/logs/postfix:/var/log/mail
        - ${APP_PATH}/data/ssl:/etc/ssl/mail
        - ${APP_PATH}/data/postfix-data:/var/spool/postfix
        - ${APP_PATH}/data/rspamd-data:/var/lib/rspamd
        - ${APP_PATH}/data/postgresql-socket:/var/run/postgresql
      environment:
        - TZ=${TZ}
        - DBNAME=${DBNAME}
        - DBUSER=${DBUSER}
        - DBPASS=${DBPASS}
        - REDISPASS=${REDISPASS}
        - BILLIONMAIL_HOSTNAME=${BILLIONMAIL_HOSTNAME}
      cap_add:
        - NET_BIND_SERVICE
      ports:
        - "${SMTP_PORT:-25}:25"
        - "${SMTPS_PORT:-465}:465"
        - "${SUBMISSION_PORT:-587}:587"
      restart: always
      labels:
        createdBy: "bt_apps"

    webmail-billionmail:
      image: roundcube/roundcubemail:1.6.10-fpm-alpine
      hostname: roundcube
      depends_on:
        - pgsql-billionmail
        - dovecot-billionmail
        - postfix-billionmail
      volumes:
        - ${APP_PATH}/data/webmail-data:/var/www/html
        - ${APP_PATH}/conf/webmail/mime.types:/var/roundcube/config/mime.types
        - ${APP_PATH}/conf/webmail:/var/roundcube/config
        - ${APP_PATH}/conf/php:/usr/local/etc
        - ${APP_PATH}/data/php-sock/:/var/run/
      environment:
        - TZ=${TZ}
        - ROUNDCUBEMAIL_DB_TYPE=pgsql
        - ROUNDCUBEMAIL_DB_HOST=pgsql
        - ROUNDCUBEMAIL_DB_NAME=${DBNAME}
        - ROUNDCUBEMAIL_DB_USER=${DBUSER}
        - ROUNDCUBEMAIL_DB_PASSWORD=${DBPASS}
        - ROUNDCUBEMAIL_DEFAULT_HOST=dovecot
        - ROUNDCUBEMAIL_DEFAULT_PORT=${IMAP_PORT:-143}
        - ROUNDCUBEMAIL_SMTP_SERVER=postfix
        - ROUNDCUBEMAIL_SMTP_PORT=${SMTP_PORT:-25}
        - ROUNDCUBEMAIL_REQUEST_PATH=/roundcube
      restart: always
      labels:
        createdBy: "bt_apps"

    BT_SERVICE_NAME6:
      image: billionmail/core:${VERSION}
      hostname: core-manage
      depends_on:
        - pgsql-billionmail
      volumes:
        - ${APP_PATH}/data/ssl:/etc/ssl/mail
        - ${APP_PATH}/ssl-self-signed:/etc/ssl/ssl-self-signed
        - ${APP_PATH}/conf/core/fail2ban/filter.d:/etc/fail2ban/filter.d
        - ${APP_PATH}/conf/core/fail2ban/jail.d:/etc/fail2ban/jail.d
        - ${APP_PATH}/data/logs/fail2ban:/var/log/fail2ban
        - ${APP_PATH}/data/postgresql-socket:/opt/billionmail/postgresql-socket
        - ${APP_PATH}/data/php-sock:/opt/billionmail/php-sock
        - ${APP_PATH}/data/rspamd-data:/opt/billionmail/rspamd-data
        - ${APP_PATH}/data/webmail-data:/opt/billionmail/webmail-data
        - ${APP_PATH}/.env:/opt/billionmail/.env
        - ${APP_PATH}/conf:/opt/billionmail/conf
        - ${APP_PATH}/data/logs:/opt/billionmail/logs
        - ${APP_PATH}/data/logs/core:/opt/billionmail/core/logs
        - ${APP_PATH}/data/core-data:/opt/billionmail/core/data
        - /var/run/docker.sock:/var/run/docker.sock:ro
      environment:
        - TZ=${TZ}
        - FAIL2BAN_INIT=${FAIL2BAN_INIT:-y}
      cap_add:
        - NET_BIND_SERVICE
        - NET_ADMIN
        - NET_RAW
      ports:
        - "${HTTP_PORT:-80}:${HTTP_PORT:-80}"
        - "${HTTPS_PORT:-443}:${HTTPS_PORT:-443}"
      restart: always
      labels:
        createdBy: "bt_apps"
