serverAddr = "127.0.0.1"
serverPort = 7000

auth.method = "token"
auth.token = "60d8a83c544e6168db"

webServer.addr = "0.0.0.0"
webServer.port = 7400
webServer.user = ""
webServer.password = ""
webServer.pprofEnable = false


# tls
#transport.tls.certFile = "/etc/frp/ssl/client.crt"
#transport.tls.keyFile = "/etc/frp/ssl/client.key"
#transport.tls.trustedCaFile = "/etc/frp/ssl/ca.crt"
