services:
  BT_SERVICE_NAME6:
    image: aoshiguchen/neutrino-proxy-server:${VERSION}
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    restart: always
    environment:
        TZ: Asia/Shanghai
        LANG: zh_CN.UTF-8
    volumes:
      - ${APP_PATH}/config:/root/neutrino-proxy/config
      - ${APP_PATH}/data:/root/neutrino-proxy/data
      - ${APP_PATH}/logs:/root/neutrino-proxy/logs
    ports:
      - ${HOST_IP}:${WEB_HTTP_PORT}:8888
      - ${HOST_IP}:${CLI_PORT}:9000
      - ${HOST_IP}:${CLI_SSL_PORT}:9002
      - 60101-60120:9101-9120
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true
