services:
  linkstack-app:
    image: linkstackorg/linkstack:latest
    restart: always
    environment:
      - TZ=${TZ}
      - PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT}
      - UPLOAD_MAX_FILESIZE=${UPLOAD_MAX_FILESIZE}
    volumes:
      - ${APP_PATH}/data/data:/opt/app/backend/data
    ports:
      - "${HOST_IP}:${LINKSTACK_WEB_PORT}:80"
    deploy:
      resources:
        limits:
          cpus: "${CPUS}"
          memory: "${MEMORY_LIMIT}"
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true