services:
  BT_SERVICE_NAME6:
    image: zoneminderhq/zoneminder:${VERSION}-el7
    #    container_name: ${CONTAINER_NAME}
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    restart: unless-stopped
    ports:
        - ${HOST_IP}:${WEB_HTTP_PORT}:80
    privileged: true
    shm_size: 512M
    environment:
        - TZ=${TZ:-Asia/Shanghai}
        - ZM_DB_USER=${MYSQL_USER}
        - ZM_DB_PASS=${MYSQL_PASSWORD}
        - ZM_DB_NAME=${MYSQL_DATABASE}
        - ZM_DB_HOST=${MYSQL_HOST_IP}
    volumes:
        - ${APP_PATH}/events:/var/cache/zoneminder/events
        - ${APP_PATH}/images:/var/cache/zoneminder/images
#        - ${APP_PATH}/mysql:/var/lib/mysql
        - ${APP_PATH}/logs:/var/log/zm
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true