services:
  xiaomusic:
    image: hanxi/xiaomusic
    ports:
      - "${HOST_IP}:${XIAOMUSIC_WEB_PORT}:8090"
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ${APP_PATH}/data/music:/app/music
      - ${APP_PATH}/data/conf:/app/conf
    deploy:
      resources:
        limits:
          cpus: "${CPUS}"
          memory: "${MEMORY_LIMIT}"
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true