services:
  BT_SERVICE_NAME6:
    image: zhenorzz/goploy:${VERSION}
    #    container_name: ${CONTAINER_NAME}
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    restart: always
    ports:
      - ${HOST_IP}:${WEB_HTTP_PORT}:80
    environment:
      - DB_HOST=${MYSQL_HOST_IP}
      - DB_USER=${MYSQL_USER}
      - DB_USER_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
    volumes:
      - ${APP_PATH}/.ssh:/root/.ssh
      - ${APP_PATH}/hosts:/etc/hosts
      - ${APP_PATH}/repository:/opt/goploy/repository
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true