services:
  BT_SERVICE_NAME6:
    image: phpmyadmin:${VERSION}
    #    container_name: ${CONTAINER_NAME}
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    ports:
      - ${HOST_IP}:${WEB_HTTP_PORT}:80
    environment:
      - PMA_ARBITRARY=1
      - MAX_EXECUTION_TIME=${MAX_EXECUTION_TIME}
      - MEMORY_LIMIT=${PHP_MEMORY_LIMIT}
      - UPLOAD_LIMIT=${UPLOAD_LIMIT}
    restart: always
    volumes:
      - ${APP_PATH}/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ${APP_PATH}/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true