services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${MYSQL_DATABASE}
      POSTGRES_PASSWORD: ${MYSQL_PASSWORD}
      POSTGRES_USER: ${MYSQL_USER}
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - ${APP_PATH}/data:/var/lib/postgresql/data
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

  BT_SERVICE_NAME6:
    image: ghcr.io/requarks/wiki:${VERSION}
    #    container_name: ${CONTAINER_NAME}
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    depends_on:
      - db
    environment:
      DB_TYPE: ${DB_TYPE}
      DB_HOST: ${MYSQL_HOST_IP}
      DB_PORT: ${MYSQL_PORT}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
    restart: unless-stopped
    ports:
      - ${HOST_IP}:${WEB_HTTP_PORT}:3000
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true