services:
  BT_SERVICE_NAME6:
    image: privoce/vocechat-server:${VERSION}
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    restart: always        
    ports:
      - ${HOST_IP}:${WEB_HTTP_PORT}:3000
    volumes:
      - ${APP_PATH}/data:/home/vocechat-server/data
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net
      
networks:
  baota_net:
    external: true