services:
  retroarch:
    image: inglebard/retroarch-web:latest
    ports:
      - "${HOST_IP}:${RETROARCH_WEB_PORT}:80"
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ${APP_PATH}/data/games:/var/lib/retroarch/assets
    deploy:
      resources:
        limits:
          cpus: "${CPUS}"
          memory: "${MEMORY_LIMIT}"
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true