services:
  BT_SERVICE_NAME6:
    image: jeessy/ddns-go:${VERSION}
    #    container_name: ${CONTAINER_NAME}
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    restart: always
    ports:
      - ${HOST_IP}:${DDNS_PORT}:9876
    volumes:
      - ${APP_PATH}/data:/root
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true