services:
  daedalos:
    image: wbsu2003/daedalos
    restart: always
    ports:
      - "${HOST_IP}:${DAEDALOS_WEB_PORT}:3000"
    volumes:
      - ${APP_PATH}/data/retro_games:/games # 老游戏存储目录
      - ${APP_PATH}/data/winamp_music:/music # 音乐文件目录
    deploy:
      resources:
        limits:
          cpus: "${CPUS}"
          memory: "${MEMORY_LIMIT}"
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true