services:
  libretranslate:
    image: libretranslate/libretranslate:latest
    ports:
      - "${HOST_IP}:${WEB_HTTP_PORT}:5000"
    restart: always
    healthcheck:
      test: ['CMD-SHELL', './venv/bin/python scripts/healthcheck.py']
      interval: 10s
      timeout: 4s
      retries: 4
      start_period: 5s
    environment:
      - LT_LOAD_ONLY=en,zh  # 只加载中英文模型
    deploy:
      resources:
        limits:
          memory: 4096M
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true