services:
  koillection-web:
    image: koillection/koillection:latest
    ports:
      - "${HOST_IP}:${WEB_HTTP_PORT}:80"
    volumes:
      - ${APP_PATH}/data/uploads:/var/www/koillection/public/uploads
    environment:
      - DB_DRIVER=${DB_DRIVER}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=5432
      - DB_VERSION=15
    depends_on:
      - koillection-db
    deploy:
      resources:
        limits:
          cpus: "${CPUS}"
          memory: "${MEMORY_LIMIT}"
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net
 
  koillection-db:
    image: postgres:15
    volumes:
      - ${APP_PATH}/data/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    deploy:
      resources:
        limits:
          cpus: "${CPUS}"
          memory: "${MEMORY_LIMIT}"
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true