services:
  BT_SERVICE_NAME6:
    image: xnx3/tcdn:${VERSION}
    restart: always
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    ports:
      - ${HOST_IP}:${WEB_HTTP_PORT}:80
    volumes:
      - ${APP_PATH}/logs:/mnt/tcdn/logs  # 将宿主机日志目录挂载到容器内
      - ${APP_PATH}/config.properties:/mnt/tcdn/config.properties  # 宿主机文件挂载到容器内
      - ${APP_PATH}/headers.conf:/mnt/tcdn/headers.conf  # 宿主机文件挂载到容器内
      - ${APP_PATH}/cache:/mnt/tcdn/cache             # 宿主机目录挂载到容器内
      - ${APP_PATH}/redis/datafile/:/mnt/redis/datafile/  # 宿主机目录挂载到容器内
    environment:
      - TZ=Asia/Shanghai
      - TCDN_HTML_KEY=${TCDN_HTML_KEY}
      - TCDN_JSPARSER_KEY=${TCDN_JSPARSER_KEY}
      - TCDN_TOKEN=${TCDN_TOKEN}
    command: bash -c "/mnt/tcdn/update_config.sh && /mnt/redis/src/redis-server /mnt/redis/redis.conf && /mnt/tcdn/start.sh && tail -f /mnt/tcdn/logs/tcdn.log"
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true
