services:
  dashy-app:
    image: lissy93/dashy:latest
    restart: always
    volumes:
      - ${APP_PATH}/data/conf.yml:/app/public/conf.yml
    ports:
      - "${HOST_IP}:${DASHY_WEB_PORT}:8080"
    deploy:
      resources:
        limits:
          cpus: "${CPUS}"
          memory: "${MEMORY_LIMIT}"
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true