services:
  dzzoffice-db:
    image: mariadb:lts
    command: --transaction-isolation=READ-COMMITTED
    volumes:
      - ${APP_PATH}/data/db:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
    deploy:
      resources:
        limits:
          cpus: "${CPUS}"
          memory: "${MEMORY_LIMIT}"
    labels:
      createdBy: "bt_apps"

  dzzoffice-app:
    image: xiaohu2023/dzzoffice
    ports:
      - "${HOST_IP}:${WEB_PORT}:80"
    volumes:
      - ${APP_PATH}/data/site:/var/www/html
    restart: always
    environment:
      - MYSQL_HOST=dzzoffice-db
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
    depends_on:
      - dzzoffice-db
    deploy:
      resources:
        limits:
          cpus: "${CPUS}"
          memory: "${MEMORY_LIMIT}"
    labels:
      createdBy: "bt_apps"

networks:
  baota_net:
    external: true