services:
  BT_SERVICE_NAME6:
    image: huolalatech/page-spy-web:${VERSION}
    restart: always        
    ports:
      - ${HOST_IP}:${WEB_HTTP_PORT}:6752
    volumes:
      - ${APP_PATH}/log:/app/log
      - ${APP_PATH}/data:/app/data
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true
