services:
  pdf2zh:
    image: byaidu/pdf2zh:latest
    ports:
      - "${HOST_IP}:${WEB_HTTP_PORT}:7860"
    restart: always
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          cpus: "${CPUS}"
          memory: "${MEMORY_LIMIT}"
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true