services:
  # Tailchat Core Services
  service-core:
    build:
      context: .
    image: moonrailgun/tailchat
    restart: unless-stopped
    env_file: docker-compose.env
    environment:
      SERVICES: core/gateway,core/user/*.service.js,core/group/*.service.js,core/chat/*.service.js,core/file,core/plugin/registry,core/config
      PORT: 3000
    depends_on:
      - mongo
      - redis
      - minio
    labels:
      - "createdBy=bt_apps"
      - "traefik.enable=true"
      - "traefik.http.routers.api-gw.rule=PathPrefix(`/`)"
      - "traefik.http.services.api-gw.loadbalancer.server.port=3000"
    networks:
      - baota_net

  # Open Platform
  service-openapi:
    build:
      context: .
    image: moonrailgun/tailchat
    restart: unless-stopped
    env_file: docker-compose.env
    environment:
      SERVICES: openapi/app,openapi/bot,openapi/integration,openapi/oidc/oidc
      OPENAPI_PORT: 3003
      OPENAPI_UNDER_PROXY: "true"
    depends_on:
      - mongo
      - redis
      - minio
    labels:
      - "createdBy=bt_apps"
      - "traefik.enable=true"
      - "traefik.http.routers.openapi-oidc.rule=PathPrefix(`/open`)"
      - "traefik.http.services.openapi-oidc.loadbalancer.server.port=3003"
    networks:
      - baota_net

  # Plugin Service (All Plugins)
  service-all-plugins:
    build:
      context: .
    image: moonrailgun/tailchat
    restart: unless-stopped
    env_file: docker-compose.env
    environment:
      SERVICEDIR: plugins
    depends_on:
      - mongo
      - redis
      - minio
    labels:
      - "createdBy=bt_apps"
    networks:
      - baota_net

  # Database
  mongo:
    image: mongo:4
    restart: on-failure
    volumes:
      - ${APP_PATH}/data:/data/db
    labels:
      - "createdBy=bt_apps"
    networks:
      - baota_net


  # Data cache and Transporter
  redis:
    image: redis:alpine
    restart: on-failure
    labels:
      - "createdBy=bt_apps"
    networks:
      - baota_net


  # Persist Storage
  minio:
    image: minio/minio
    restart: on-failure
    environment:
      MINIO_ROOT_USER: tailchat
      MINIO_ROOT_PASSWORD: com.msgbyte.tailchat
    volumes:
      - ${APP_PATH}/storage:/data
    command: minio server /data --console-address ":9001"
    labels:
      - "createdBy=bt_apps"
    networks:
      - baota_net

  # Router
  BT_SERVICE_NAME6:
    image: traefik:v2.1
    restart: unless-stopped
    command:
      - "--api.insecure=true" # Don't do that in production!
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.web.forwardedHeaders.insecure" # Not good
    ports:
      - ${HOST_IP}:${WEB_HTTP_PORT}:80
      - 127.0.0.1:11001:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "createdBy=bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true
