services:
  BT_SERVICE_NAME6:
    image: yourls:${VERSION}
    #    container_name: ${CONTAINER_NAME}
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    restart: always
    ports:
      - ${HOST_IP}:${WEB_HTTP_PORT}:80
    environment:
      - YOURLS_SITE=${YOURLS_SITE}
      - YOURLS_USER=${USERNAME}
      - YOURLS_PASS=${PASSWORD}
      - YOURLS_DB_HOST=${MYSQL_HOST_IP}:${MYSQL_PORT}
      - YOURLS_DB_NAME=${MYSQL_DATABASE}
      - YOURLS_DB_USER=${MYSQL_USER}
      - YOURLS_DB_PASS=${MYSQL_PASSWORD}
      - YOURLS_DB_PREFIX=${YOURLS_DB_PREFIX}
    volumes:
      - ${APP_PATH}/data:/var/www/html
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true