services:
  moodist:
    image: ghcr.1ms.run/remvze/moodist:latest
    container_name: moodist
    restart: always
    ports:
      - "${HOST_IP}:${WEB_HTTP_PORT}:8080"
    logging:
      options:
        max-size: 1g
    deploy:
      resources:
        limits:
          cpus: "${CPUS}"
          memory: "${MEMORY_LIMIT}"
    labels:
      createdBy: "bt_apps"
networks:
  baota_net:
    external: true