services:
  BT_SERVICE_NAME6:
    image: rockchin/langbot:${VERSION}
    #    container_name: ${CONTAINER_NAME}
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    restart: always
    ports:
      - ${HOST_IP}:${WEB_HTTP_PORT}:5300
      - 2280-2290:2280-2290    
    volumes:
      - ${APP_PATH}/data:/app/data
      - ${APP_PATH}/plugins:/app/plugins
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

  langbot_plugin_runtime:
    image: rockchin/langbot:latest
    volumes:
      - ${APP_PATH}/data/plugins:/app/data/plugins
#    ports:
#      - 5401:5401
    restart: on-failure
    environment:
      - TZ=Asia/Shanghai
    command: [ "uv", "run", "-m", "langbot_plugin.cli.__init__", "rt" ]
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net
networks:
  baota_net:
    external: true