services:
  BT_SERVICE_NAME6:
    image: registry.cn-shanghai.aliyuncs.com/topthink/bot:${VERSION}
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}    
    restart: always
    command:
      - app:run
    ports:
      - ${HOST_IP}:${WEB_HTTP_PORT}:80
    environment:
      PHP_DB_HOST: ${SERVICE_NAME}_mysql
      PHP_REDIS_HOST: ${SERVICE_NAME}_redis
      PHP_QDRANT_HOST: ${SERVICE_NAME}_qdrant
      PHP_LICENSE: ${API_KEY} #授权码 https://doc.topthink.com/@thinkbot-deploy/apply.html
      PHP_APP_URL: ${THINKBOT_URL} #应用访问地址
    volumes:
      - ${APP_PATH}/app/storage:/opt/htdocs/storage
    depends_on:
      - mysql
      - redis
      - qdrant
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

  qdrant:
    image: registry.cn-shanghai.aliyuncs.com/topopen/qdrant:latest
    restart: always
    volumes:
      - ${APP_PATH}/app/qdrant:/qdrant/storage
    labels:
      createdBy: "bt_apps"
    networks:
      baota_net:
        aliases:
          - ${SERVICE_NAME}_qdrant

  redis:
    image: registry.cn-shanghai.aliyuncs.com/topopen/redis:latest
    restart: always
    volumes:
      - ${APP_PATH}/app/redis:/data
    labels:
      createdBy: "bt_apps"
    networks:
      baota_net:
        aliases:
          - ${SERVICE_NAME}_redis

  mysql:
    image: registry.cn-shanghai.aliyuncs.com/topopen/mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bot
    volumes:
      - ${APP_PATH}/app/mysql:/var/lib/mysql
    labels:
      createdBy: "bt_apps"
    networks:
      baota_net:
        aliases:
          - ${SERVICE_NAME}_mysql

networks:
  baota_net:
    external: true