services:
  kotaemon:
    image: ghcr.1ms.run/cinnamon/kotaemon:main-full
    ports:
      - "${HOST_IP}:${WEB_HTTP_PORT}:7860"
    environment:
      - GRADIO_SERVER_NAME=${GRADIO_SERVER_NAME}
      - GRADIO_SERVER_PORT=${GRADIO_SERVER_PORT}
    volumes:
      - ${APP_PATH}/data/ktem_app_data:/app/ktem_app_data
    restart: always
    deploy:
      resources:
        limits:
          cpus: "${CPUS}"
          memory: "${MEMORY_LIMIT}"
    labels:
      createdBy: "bt_apps"

networks:
  default:
    name: baota_net
    external: true