services:
  BT_SERVICE_NAME6:
    image: nocodb/nocodb:${VERSION}
    #    container_name: ${CONTAINER_NAME}
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    restart: always
    ports:
      - ${HOST_IP}:${WEB_HTTP_PORT}:8080
    environment:
      NC_DB: "${DB_TYPE}://${DB_HOST}:${DB_PORT}?u=${DB_USERNAME}&p=${DB_PASSWORD}&d=${DB_NAME}"
    volumes:
      - ${APP_PATH}/data:/usr/app/data
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true