services:
  filestash:
    image: machines/filestash:latest
    ports:
      - "${HOST_IP}:${FILESTASH_WEB_PORT}:8334"
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ${APP_PATH}/data/state:/app/data/state
      - ${APP_PATH}/data/config:/app/data/config
    deploy:
      resources:
        limits:
          cpus: "${CPUS}"
          memory: "${MEMORY_LIMIT}"
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true