services:
  BT_SERVICE_NAME6:
    image: prom/prometheus:${VERSION}
    #    container_name: ${CONTAINER_NAME}
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    ports:
        - ${HOST_IP}:${WEB_HTTP_PORT}:9090
    restart: always
    volumes:
        - ${APP_PATH}/conf:/etc/prometheus/
        - ${APP_PATH}/prometheus:/prometheus
    command:
        - --config.file=/etc/prometheus/prometheus.yml
        - --storage.tsdb.path=/prometheus
        - --web.console.libraries=/etc/prometheus/console_libraries
        - --web.console.templates=/etc/prometheus/consoles
        - --storage.tsdb.retention=200h
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true