services:
  lsky-pro:
    image: 0xxb/lsky-pro:latest
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    ports:
      - ${HOST_IP}:${WEB_HTTP_PORT}:8000
    volumes:
      - ${APP_PATH}/data/appdata:/app/storage/app
    restart: unless-stopped
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true