services:
  BT_SERVICE_NAME6:
    image: espocrm/espocrm:${VERSION}
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    environment:
      ESPOCRM_DATABASE_PLATFORM: Mysql
      ESPOCRM_DATABASE_HOST: ${MYSQL_HOST_IP}
      ESPOCRM_DATABASE_USER: ${MYSQL_USER}
      ESPOCRM_DATABASE_NAME: ${MYSQL_DATABASE}
      ESPOCRM_DATABASE_PASSWORD: ${MYSQL_PASSWORD}
      ESPOCRM_ADMIN_USERNAME: ${ESPOCRM_USER_NAME}
      ESPOCRM_ADMIN_PASSWORD: ${ESPOCRM_USER_PASSWORD}
      ESPOCRM_SITE_URL: ${ESPOCRM_EXTERNAL_URL}
    volumes:
      - ${APP_PATH}/espocrm:/var/www/html
    restart: always
    ports:
      - ${HOST_IP}:${WEB_HTTP_PORT}:80
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net


  espocrm-daemon:
    image: espocrm/espocrm:${VERSION}
    volumes:
      - ${APP_PATH}/espocrm:/var/www/html
    restart: always
    depends_on:
      - BT_SERVICE_NAME6
    entrypoint: docker-daemon.sh
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net
    

  espocrm-websocket:
    image: espocrm/espocrm:${VERSION}
    environment:
      ESPOCRM_CONFIG_USE_WEB_SOCKET: "true"
      ESPOCRM_CONFIG_WEB_SOCKET_URL: "ws://localhost:${WSS_PORT}"
      ESPOCRM_CONFIG_WEB_SOCKET_ZERO_M_Q_SUBSCRIBER_DSN: "tcp://*:7777"
      ESPOCRM_CONFIG_WEB_SOCKET_ZERO_M_Q_SUBMISSION_DSN: "tcp://espocrm-websocket:7777"
    volumes:
      - ${APP_PATH}/espocrm:/var/www/html
    restart: always
    depends_on:
      - BT_SERVICE_NAME6
    entrypoint: docker-websocket.sh
    ports:
      - ${HOST_IP}:${WSS_PORT}:8080
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true
