services:
  tududi-web:
    image: chrisvel/tududi:${VERSION}
    restart: always
    ports:
      - "${HOST_IP}:${TUDUDI_WEB_PORT}:3002"
    volumes:
      - ${APP_PATH}/data:/usr/src/app/tududi_db
    environment:
      - TUDUDI_USER_EMAIL=${TUDUDI_USER_EMAIL}
      - TUDUDI_USER_PASSWORD=${TUDUDI_USER_PASSWORD}
      - TUDUDI_SESSION_SECRET=${TUDUDI_SESSION_SECRET}
    deploy:
      resources:
        limits:
          cpus: "${CPUS}"
          memory: "${MEMORY_LIMIT}"
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true