services:
  BT_SERVICE_NAME6:
    image: hyperf/hyperf:8.1-alpine-v3.18-swoole
    #    container_name: ${CONTAINER_NAME}
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    restart: always
    working_dir: /data/project
    stdin_open: true
    tty: true
    privileged: true
    user: root
    entrypoint: sh -c "ls -alsh /data/project && if [ ! -d 'hyperf-skeleton' ]; then composer create-project hyperf/hyperf-skeleton --no-interaction;fi;php ./hyperf-skeleton/bin/hyperf.php start"
    ports:
      - ${HOST_IP}:${WEB_HTTP_PORT}:9501
    volumes:
      - ${APP_PATH}/skeleton:/data/project
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true
