services:
  tv-iptv-generator:
    image: guovern/tv-driver
    ports:
      - "${HOST_IP}:${WEB_HTTP_PORT}:8000"
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ${APP_PATH}/data/config:/tv-driver/config
      - ${APP_PATH}/data/output:/tv-driver/output
    deploy:
      resources:
        limits:
          cpus: "${CPUS}"
          memory: "${MEMORY_LIMIT}"
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true