services:
  BT_SERVICE_NAME6:
    image: registry.cn-shanghai.aliyuncs.com/youdeyunke/ce:panel
    restart: on-failure:3
    ports:
      - ${HOST_IP}:${WEB_HTTP_PORT}:80
    environment:
      TZ: "Asia/Shanghai"
      LANG: "C.UTF-8"
    depends_on:
      - server
    volumes:
      - /tmp:/tmp
      - ${APP_PATH}/upload:/app/filestore
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

  server:
    image: registry.cn-shanghai.aliyuncs.com/youdeyunke/ce:server
    platform: "linux/x86_64"        # 如果是m芯片必须加这个
    privileged: true
    restart: always
    expose:
      - 8080
    environment:
      TZ: "Asia/Shanghai"
      LANG: "C.UTF-8"
    depends_on:
      - redis
      - db
    volumes:
      - /tmp:/tmp
      - ${APP_PATH}/upload:/app/upload/
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net


  redis:
    restart: "always"
    image: registry.cn-shanghai.aliyuncs.com/youdeyunke/common:redis-4.0
    command: redis-server --bind 0.0.0.0 --appendonly yes
    expose:
      - 6379
    environment:
      TZ: "Asia/Shanghai"
      LANG: "C.UTF-8"
    volumes:
      - ${APP_PATH}/redis:/data
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

  db:
    restart: "always"
    image: registry.cn-shanghai.aliyuncs.com/youdeyunke/common:mysql-8.0.3
    expose:
      - 3306
    volumes:
      - ${APP_PATH}/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: udyk_community
      LANG: "C.UTF-8"
      TZ: "Asia/Shanghai"
      MYSQL_ROOT_PASSWORD: "udyk@2023"
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true
      