services:
  BT_SERVICE_NAME6:
    image: easysoft/zentao:${VERSION}
    #    container_name: ${CONTAINER_NAME}
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    ports:
      - ${HOST_IP}:${WEB_HTTP_PORT}:80
    environment:
      - MYSQL_INTERNAL=false
      - ZT_MYSQL_HOST=${ZT_MYSQL_HOST}
      - ZT_MYSQL_PORT=${ZT_MYSQL_PORT}
      - ZT_MYSQL_DB=${ZT_MYSQL_DB}
      - ZT_MYSQL_USER=${ZT_MYSQL_USER}
      - ZT_MYSQL_PASSWORD=${ZT_MYSQL_PASSWORD}
    restart: always
    volumes:
      - ${APP_PATH}/data:/data
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true