services:
  BT_SERVICE_NAME6:
    image: dpage/pgadmin4:${VERSION}
    #    container_name: ${CONTAINER_NAME}
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PASSWORD}
    ports:
      - ${HOST_IP}:${WEB_HTTP_PORT}:80
    volumes:
      - ${APP_PATH}/data:/var/lib/pgadmin
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true