services:
  BT_SERVICE_NAME6:
    image: linuxserver/freshrss:${VERSION}
    #    container_name: ${CONTAINER_NAME}
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    restart: always
    ports:
      - ${HOST_IP}:${WEB_HTTP_PORT}:80
    environment:
        - PUID=1000
        - PGID=1000
    volumes:
        - ${APP_PATH}/data:/config
        - /etc/localtime:/etc/localtime:ro
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true