services:
  ujcms:
    image: ujcms/ujcms:${VERSION}
    restart: always
    ports:
      - ${HOST_IP}:${WEB_HTTP_PORT}:8080
    environment:
      UJCMS_DB_HOST: ${SERVICE_NAME}_mysql
      UJCMS_DB_PORT: 3306
      UJCMS_DB_NAME: ujcms
      UJCMS_DB_USER: ujcms
      UJCMS_DB_PASSWORD: my-secret-pw
      UJCMS_OFFICE_ENABLED: true
    depends_on:
      mysql:
        condition: service_healthy
        restart: true
    # volumes:
    # - ${APP_PATH}/data/config:/ujcms/config
    # - ${APP_PATH}/data/static:/ujcms/static
    networks:
      - baota_net
    labels:
      createdBy: "bt_apps"

  mysql:
    image: mysql:8.3.0
    restart: always
    healthcheck: # Health check definition
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    # ports:
    #  - 53306:3306
    environment:
      MYSQL_DATABASE: ujcms
      MYSQL_USER: ujcms
      MYSQL_PASSWORD: my-secret-pw
      MYSQL_ROOT_PASSWORD: password
#      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
     - ${APP_PATH}/data/mysql:/var/lib/mysql
    networks:
      baota_net:
        aliases:
          - ${SERVICE_NAME}_mysql
    labels:
      createdBy: "bt_apps"

networks:
  baota_net:
    external: true