services:
  videotogether:
    image: pigeonpig/videotogether
    restart: always
    ports:
      - "${HOST_IP}:${VIDEOTOGETHER_WEB_PORT}:5000"
    volumes:
      - ${APP_PATH}/data/release_host:/app/source/extension/config/release_host
    deploy:
      resources:
        limits:
          cpus: "${CPUS}"
          memory: "${MEMORY_LIMIT}"
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true