services:
  mariadb:
    image: bitnami/mariadb:${VERSION}
    #    container_name: ${CONTAINER_NAME}
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_suitecrm
      - MARIADB_DATABASE=bitnami_suitecrm
      - MARIADB_PASSWORD=bitnami123
    volumes:
      - ${APP_PATH}/db_data:/var/lib/mysql
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net      
      
      
  BT_SERVICE_NAME6:
    container_name: suitecrm_web
    image: bitnami/suitecrm:7
    ports:
      - ${HOST_IP}:${WEB_HTTP_PORT}:8080
      - ${HOST_IP}:${WEB_HTTPS_PORT}:8443
    environment:
      - SUITECRM_DATABASE_HOST=mariadb
      - SUITECRM_DATABASE_PORT_NUMBER=3306
      - SUITECRM_DATABASE_USER=bn_suitecrm
      - SUITECRM_DATABASE_NAME=bitnami_suitecrm
      - SUITECRM_DATABASE_PASSWORD=bitnami123
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - SUITECRM_USERNAME=${SUITECRM_USERNAME}
      - SUITECRM_PASSWORD=${SUITECRM_PASSWORD}
      - SUITECRM_EMAIL=${SUITECRM_EMAIL}
    volumes:
      - ${APP_PATH}/suitecrm_data:/bitnami/suitecrm
    depends_on:
      - mariadb
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true