services:
  bt-kafka:
    image: apache/kafka:${VERSION}
    #    container_name: ${CONTAINER_NAME}
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    restart: always
    ports:
      - ${HOST_IP}:${WEB_HTTP_PORT}:9092
    environment:
      # KRaft模式核心配置（无需ZooKeeper）
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller  # 同时作为broker和controller

      # 监听配置（容器内部实际监听的地址和端口）
      # PLAINTEXT://0.0.0.0:9092：允许容器内所有IP访问9092端口（供外部客户端连接）
      # CONTROLLER://0.0.0.0:9093：控制器内部通信端口
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093

      # 对外公布的连接地址（客户端实际连接的地址）
      # 本地测试用：PLAINTEXT://localhost:9092
      # 局域网访问用：PLAINTEXT://宿主机局域网IP:9092（例如192.168.1.100）
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${EXTERNAL_IP}:9092

      # 控制器相关配置
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@bt-kafka:9093  # 控制器集群投票节点（使用容器名内部访问）

      # 主题默认配置
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1  # 偏移量主题副本数（单节点只能设1）
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0  # 禁用初始重平衡延迟（加快测试）
      - KAFKA_NUM_PARTITIONS=3  # 新建主题默认分区数
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true