services:
  BT_SERVICE_NAME6:
    image: mouday/domain-admin:${VERSION}
    #    container_name: ${CONTAINER_NAME}
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    restart: always
    ports:
      - ${HOST_IP}:${WEB_HTTP_PORT}:8000
    volumes:
      - ${APP_PATH}/database:/app/database
      - ${APP_PATH}/logs:/app/logs
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true