services:
  BT_SERVICE_NAME6:
    image: searxng/searxng:${VERSION}
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    ports:
      - ${HOST_IP}:${WEB_HTTP_PORT}:8080
    volumes:
      - ${APP_PATH}/searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=${SITE_URL:-localhost}
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true