services:
  BT_SERVICE_NAME6:
    image: hamster1963/nezha-dash:${VERSION}
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    ports:
      - ${HOST_IP}:${WEB_HTTP_PORT}:3000
    restart: always
    environment:
      - NezhaBaseUrl=${NEZHABASEURL}
      - NezhaAuth=${NEZHAAUTH}
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true