services:
  BT_SERVICE_NAME6:
    image: registry.cn-shanghai.aliyuncs.com/naibahq/nezha-dashboard:${VERSION}
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    ports:
      - ${HOST_IP}:${WEB_HTTP_PORT}:8008
    restart: always
    volumes:
      - ${APP_PATH}/data:/dashboard/data
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true