services:
  wallabag-web:
    image: wallabag/wallabag:latest
    ports:
      - "${HOST_IP}:${WEB_HTTP_PORT}:80"
    environment:
      - SYMFONY__ENV__DOMAIN_NAME=${SYMFONY__ENV__DOMAIN_NAME}
    volumes:
      - ${APP_PATH}/data/data:/var/www/wallabag/data
      - ${APP_PATH}/data/images:/var/www/wallabag/web/assets/images
    restart: always
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          cpus: "${CPUS}"
          memory: "${MEMORY_LIMIT}"
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true