services:
  shenyu-postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=shenyusql
      - POSTGRES_PASSWORD=2LPRVTbQULN8oyhyJz67
      - POSTGRES_DB=shenyu
    volumes:
      - ${APP_PATH}/create-table.sql:/docker-entrypoint-initdb.d/create-table.sql
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'psql -U shenyusql -h127.0.0.1 -p5432 -dshenyu -c "SELECT 1"',
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: always
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net
            
  BT_SERVICE_NAME6:
    image: apache/shenyu-admin:${VERSION}
    ports:
      - ${HOST_IP}:${WEB_HTTP_PORT1}:9095
    environment:
      - TZ=Asia/Beijing
      - SPRING_PROFILES_ACTIVE=pg
      - shenyu.database.init_enable=true
      - spring.datasource.username=shenyusql
      - spring.datasource.password=2LPRVTbQULN8oyhyJz67
      - spring.datasource.url=jdbc:postgresql://shenyu-postgres:5432/shenyu?useUnicode=true&characterEncoding=utf-8&useSSL=false
      - shenyu.sync.websocket.enabled=true
      - shenyu.sync.websocket.messageMaxSize=10240
      - shenyu.sync.websocket.allowOrigins=ws://localhost:9095;ws://localhost:9195;
    volumes:
      - ${APP_PATH}/admin-entrypoint.sh:/opt/shenyu-admin/entrypoint.sh
      - ${APP_PATH}/pg-connector:/opt/shenyu-admin/ext-lib
      - ${APP_PATH}/shenyu-admin/logs/:/opt/shenyu-admin/logs
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -q -O - http://localhost:9095/actuator/health | grep UP || exit 1 ",
        ]
      interval: 60s
      timeout: 60s
      retries: 10
      start_period: 30s
    restart: always
    depends_on:
      shenyu-postgres:
        condition: service_healthy
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

  shenyu-bootstrap:
    image: apache/shenyu-bootstrap:latest
    # container_name: shenyu-bootstrap
    # scale: 2
    ports:
      - ${HOST_IP}:${WEB_HTTP_PORT2}:9195
    volumes:
      - ${APP_PATH}/bootstrap-entrypoint.sh:/opt/shenyu-bootstrap/entrypoint.sh
      - ${APP_PATH}/shenyu-bootstrap/logs/:/opt/shenyu-bootstrap/logs
    environment:
      - TZ=Asia/Beijing
      - shenyu.sync.websocket.urls=ws://shenyu-admin:9095/websocket
      - shenyu.sync.websocket.allowOrigin=ws://localhost:9195
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -q -O - http://localhost:9195/actuator/health | grep UP || exit 1",
        ]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 30s
    restart: always
    depends_on:
      BT_SERVICE_NAME6:
        condition: service_healthy
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true