services:
  BT_SERVICE_NAME6:
    image: wiznote/wizserver:${VERSION}
    #    container_name: ${CONTAINER_NAME}
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    restart: always
    ports:
      - ${HOST_IP}:${WEB_HTTP_PORT}:80
      - ${HOST_IP}:${UDP_PORT}:9269/udp
    volumes:
        - ${APP_PATH}/wizdata:/wiz/storage
        - /etc/localtime:/etc/localtime:ro
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true