services:
  BT_SERVICE_NAME6:
    image: bytemark/webdav:${VERSION}
    #    container_name: ${CONTAINER_NAME}
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    restart: always
    ports:
      - ${HOST_IP}:${WEB_HTTP_PORT}:80
    environment:
      AUTH_TYPE: ${AUTH_TYPE}
      USERNAME: ${USERNAME}
      PASSWORD: ${PASSWORD}
    volumes:
      - ${VOLUME_PATH}:/var/lib/dav
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true